"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Separator } from "@/components/ui/separator"
import { Badge } from "@/components/ui/badge"
import { Brain, Lightbulb, RefreshCw, TrendingUp } from 'lucide-react'
import { useToast } from "@/components/ui/use-toast"

export function AIInsights() {
  const [isLoading, setIsLoading] = useState(false)
  const { toast } = useToast()

  const handleGenerateInsights = () => {
    setIsLoading(true)
    // Simulate API call to Claude
    setTimeout(() => {
      setIsLoading(false)
      toast({
        title: "Insights Generated",
        description: "New AI insights have been generated based on your financial data.",
      })
    }, 2000)
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold">AI-Powered Financial Insights</h2>
        <Button onClick={handleGenerateInsights} disabled={isLoading}>
          {isLoading ? (
            <>
              <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Brain className="mr-2 h-4 w-4" />
              Refresh Insights
            </>
          )}
        </Button>
      </div>
      
      <p className="text-muted-foreground">
        These insights are generated by analyzing your spending patterns and financial behavior.
      </p>
      
      <Tabs defaultValue="summary" className="space-y-4">
        <TabsList>
          <TabsTrigger value="summary">Summary</TabsTrigger>
          <TabsTrigger value="recommendations">Recommendations</TabsTrigger>
          <TabsTrigger value="anomalies">Anomalies</TabsTrigger>
        </TabsList>
        
        <TabsContent value="summary" className="space-y-4">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Monthly Financial Summary</CardTitle>
                  <CardDescription>Generated on May 15, 2025</CardDescription>
                </div>
                <Badge variant="outline" className="ml-auto">
                  AI Generated
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <h3 className="font-semibold">Overview</h3>
                <p>
                  Based on your transaction history, you've spent $2,350 this month, which is 4.1% less than last month.
                  Your top spending categories are Food ($520), Utilities ($420), and Transportation ($380).
                </p>
              </div>
              <Separator />
              <div className="space-y-2">
                <h3 className="font-semibold">Key Insights</h3>
                <ul className="space-y-2 list-disc pl-5">
                  <li>Your savings rate is 50.5%, which is excellent and above the recommended 20%.</li>
                  <li>Your restaurant spending has decreased by 15% compared to last month.</li>
                  <li>Your utility bills are 8% higher than the same period last year.</li>
                  <li>You have 3 subscription services totaling $45.97 per month.</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="recommendations" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center">
                <Lightbulb className="mr-2 h-5 w-5 text-primary" />
                Personalized Recommendations
              </CardTitle>
              <CardDescription>
                Based on your financial behavior, here are some recommendations to improve your finances
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-4">
                <li className="flex items-start gap-2">
                  <Badge className="mt-0.5 bg-emerald-500">$45</Badge>
                  <div>
                    <p className="font-medium">Cancel unused subscription services</p>
                    <p className="text-sm text-muted-foreground">You haven't used Netflix in 45 days</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <Badge className="mt-0.5 bg-emerald-500">$120</Badge>
                  <div>
                    <p className="font-medium">Reduce utility bills</p>
                    <p className="text-sm text-muted-foreground">Your electricity usage is 20% above average</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <Badge className="mt-0.5 bg-emerald-500">$85</Badge>
                  <div>
                    <p className="font-medium">Optimize dining expenses</p>
                    <p className="text-sm text-muted-foreground">
                      Reducing restaurant visits by 1 per week could save this amount
                    </p>
                  </div>
                </li>
              </ul>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Apply Recommendations to Budget</Button>
            </CardFooter>
          </Card>
        </TabsContent>
        
        <TabsContent value="anomalies" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Spending Anomalies</CardTitle>
              <CardDescription>
                Unusual spending patterns detected in your transaction history
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-4">
                <li className="flex items-start gap-2">
                  <Badge variant="destructive" className="mt-0.5">
                    High
                  </Badge>
                  <div>
                    <p className="font-medium">Unusual transaction at Amazon ($199.99)</p>
                    <p className="text-sm text-muted-foreground">This is 4x your typical Amazon purchase amount</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <Badge variant="secondary" className="mt-0.5">
                    Medium
                  </Badge>
                  <div>
                    <p className="font-medium">Multiple coffee shop purchases</p>
                    <p className="text-sm text-muted-foreground">8 transactions totaling $42.35 this week</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <Badge className="mt-0.5 bg-amber-500">Low</Badge>
                  <div>
                    <p className="font-medium">New subscription detected</p>
                    <p className="text-sm text-muted-foreground">Spotify Premium ($9.99/month) started on May 5</p>
                  </div>
                </li>
              </ul>
            </CardContent>
            <CardFooter>
              <div className="flex items-center justify-between w-full">
                <TrendingUp className="text-primary" />
                <p className="text-sm text-muted-foreground">
                  Anomalies are detected by comparing your current spending with historical patterns
                </p>
              </div>
            </CardFooter>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}